### ISSUE TITLE
Error when updating platform with manufacturer 

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot-app-device-onboarding#205] opened 2024-07-25 17:02 UTC
### Environment
* Python version:  
* Nautobot version:  
* nautobot-device-onboarding version:  4.0rc2

### Expected Behavior
Platform/manufacturer to be updated or skipped (leave as is)

### Observed Behavior

Error updating platform to include manufacturer

### Steps to Reproduce
1. Add a platform without a manufacturer
2. Use platform in Sync Device from Network job
3. Observe error when DO job tries to update the platform:

```
worker-1    | [2024-07-25 16:58:44,503: INFO/ForkPoolWorker-6] Created successfully
worker-1    | [2024-07-25 16:58:44,503: DEBUG/ForkPoolWorker-6] Attempting model update
worker-1    | [2024-07-25 16:58:44,506: ERROR/ForkPoolWorker-6] No such platform instance with PK None
worker-1    | [2024-07-25 16:58:44,521: DEBUG/ForkPoolWorker-6] nautobot.extras.jobs.run_job[b333d0a7-7026-40a0-9e1c-81ad908ebacb]: Deleted 0 file proxies
worker-1    | [2024-07-25 16:58:44,537: ERROR/ForkPoolWorker-6] Task nautobot.extras.jobs.run_job[b333d0a7-7026-40a0-9e1c-81ad908ebacb] raised unexpected: ObjectNotUpdated(ObjectCrudException('No such platform instance with PK None'))
worker-1    | Traceback (most recent call last):
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/contrib/model.py", line 69, in get_from_db
worker-1    |     return self.diffsync.get_from_orm_cache({"pk": self.pk}, self._model)
worker-1    |   File "/source/nautobot_device_onboarding/diffsync/adapters/sync_devices_adapters.py", line 57, in get_from_orm_cache
worker-1    |     self._cache[model_cache_key][parameter_set] = model_class.objects.get(**dict(parameter_set))
worker-1    |   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
worker-1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
worker-1    |     raise self.model.DoesNotExist(
worker-1    | nautobot.dcim.models.devices.Platform.DoesNotExist: Platform matching query does not exist.
worker-1    | 
worker-1    | The above exception was the direct cause of the following exception:
worker-1    | 
worker-1    | Traceback (most recent call last):
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/contrib/model.py", line 76, in update
worker-1    |     obj = self.get_from_db()
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/contrib/model.py", line 71, in get_from_db
worker-1    |     raise ObjectCrudException(f"No such {self._model._meta.verbose_name} instance with PK {self.pk}") from error
worker-1    | diffsync.exceptions.ObjectCrudException: No such platform instance with PK None
worker-1    | 
worker-1    | The above exception was the direct cause of the following exception:
worker-1    | 
worker-1    | Traceback (most recent call last):
worker-1    |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
worker-1    |     R = retval = fun(*args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
worker-1    |     return self.run(*args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
worker-1    |     result = job(*args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 149, in __call__
worker-1    |     return self.run(*args, **deserialized_kwargs)
worker-1    |   File "/source/nautobot_device_onboarding/jobs.py", line 513, in run
worker-1    |     super().run(dryrun, memory_profiling, *args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 317, in run
worker-1    |     self.sync_data(memory_profiling)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 166, in sync_data
worker-1    |     self.execute_sync()
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 98, in execute_sync
worker-1    |     self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/diffsync/__init__.py", line 601, in sync_to
worker-1    |     return target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/diffsync/__init__.py", line 573, in sync_from
worker-1    |     result = syncer.perform_sync()
worker-1    |   File "/usr/local/lib/python3.10/site-packages/diffsync/helpers.py", line 329, in perform_sync
worker-1    |     changed |= self.sync_diff_element(element)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/diffsync/helpers.py", line 379, in sync_diff_element
worker-1    |     changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/diffsync/helpers.py", line 432, in sync_model
worker-1    |     dst_model = dst_model.update(attrs=attrs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/nautobot_ssot/contrib/model.py", line 79, in update
worker-1    |     raise ObjectNotUpdated(error) from error
worker-1    | diffsync.exceptions.ObjectNotUpdated: No such platform instance with PK None

```

**Comment by gsnider2195** [comment] 2024-10-25 18:51
Closing as duplicate of #195

**Closed by gsnider2195** 2024-10-25 18:51 UTC
