### ISSUE TITLE
Docs: Add an example CSV file for bulk onboarding

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-onboarding#260] opened 2024-10-21 14:14 UTC
### Environment
* Python version:  3.11
* Nautobot version:  2.2.3
* nautobot-device-onboarding version: 4.x
* ntc-templates version: 6.0

In the Using the App section, [here](https://docs.nautobot.com/projects/device-onboarding/en/latest/user/app_use_cases/?h=bulk#onboard-a-new-device-using-sync-devices-from-network-job:~:text=This%20SSoT%20job%20supports%20a%20bulk%20CSV%20execution%20option%20to%20speed%20up%20this%20process. ) we should add an example CSV with all the columns etc.  To help users get up and running quicker.

**Comment by scetron** [comment] 2024-11-01 19:27
Duplicate of #234

**Closed by scetron** 2024-11-01 19:27 UTC
